### ISSUE TITLE
parse_requirements requires a `session` argument

### ISSUE THREAD

**Issue by fiatjaf** [juanpabloaj/pip-init#11]
When installing a package whose `setup.py` was made with `pip-init` on Heroku, this happens:

```
         Downloading went-0.0.1.tar.gz
           Traceback (most recent call last):
             File "<string>", line 20, in <module>
             File "/tmp/pip-build-S8sOPu/went/setup.py", line 7, in <module>
               install_requires = [str(r.req) for r in requirements]
             File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements
               "parse_requirements() missing 1 required keyword argument: "
           TypeError: parse_requirements() missing 1 required keyword argument: 'session'
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):

             File "<string>", line 20, in <module>

             File "/tmp/pip-build-S8sOPu/went/setup.py", line 7, in <module>

               install_requires = [str(r.req) for r in requirements]

             File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements

               "parse_requirements() missing 1 required keyword argument: "

           TypeError: parse_requirements() missing 1 required keyword argument: 'session'

           ----------------------------------------
           Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-S8sOPu/went
```

This seems to be true for newer versions of `pip`. However, the following line made it work:

``` python
import pip
requirements = parse_requirements("requirements.txt", session=pip.download.PipSession())
```

Based on https://github.com/jmcarp/robobrowser/pull/32

**Comment by juanpabloaj** [comment]
@fiatjaf to generate a more simple `setup.py` file, in the last versions of pip-init, I removed the line with `parse_requirements`.

by the way, maybe you like this post about the `requirements.txt` file.

https://caremad.io/2013/07/setup-vs-requirement/
