### ISSUE TITLE
UnicodeEncodeError: author with accent

### ISSUE THREAD

**Issue by e3krisztian** [juanpabloaj/pip-init#13]
``` sh
$ git config --global user.name
Fekete Krisztián
```

``` python
~/projects/a_pkg$ pip-init 
name (a_pkg): 
version (0.1.0): 
description (A pip package): 
license (MIT): 
Traceback (most recent call last):
  File "/home/kr/.virtualenvs/d8d8bea9-a777-4acb-b6c6-bafe857fbe81/bin/pip-init", line 9, in <module>
    load_entry_point('pip-init==0.2.0', 'console_scripts', 'pip-init')()
  File "/home/kr/.virtualenvs/d8d8bea9-a777-4acb-b6c6-bafe857fbe81/local/lib/python2.7/site-packages/pip_init/__init__.py", line 71, in main
    input_msg = input_message(field_name, default_value)
  File "/home/kr/.virtualenvs/d8d8bea9-a777-4acb-b6c6-bafe857fbe81/local/lib/python2.7/site-packages/pip_init/__init__.py", line 12, in input_message
    return '{} ({}): '.format(field_name, default_value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 14: ordinal not in range(128)
```

**Comment by juanpabloaj** [comment]
@krisztianfekete in version 0.2.1 I uploaded the change made in commit 2003a7db5a6b6c117171a8d0b13bf1aecc9df015

**Comment by e3krisztian** [comment]
Thanks for looking into this!

I confirm, that the fix indeed works as long as it generates a `setup.py`, that looks right,
but unfortunately the generated `setup.py` is not valid for me:

``` python
$ python setup.py 
  File "setup.py", line 13
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 13, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

To fix it the first 2 lines of the `setup.py` script should have a comment as 

``` python
# coding: utf-8
```

**Comment by juanpabloaj** [comment]
in a few hours, when I get home, I try to fix. Or if you like you can make a pull request ;)

**Comment by e3krisztian** [comment]
see #14

**Comment by e3krisztian** [comment]
@juanpabloaj thanks for merging, I have tested and it now works for me!
